// ==========================================
// TOP-LEVEL BUILD FILE
// Android Gradle Plugin 8.3.2
// Gradle 8.5
// ==========================================

buildscript {

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
    }
}


// ==========================================
// ALL PROJECTS
// ==========================================

allprojects {

    repositories {
        google()
        mavenCentral()
    }
}